package com.hmi.kiddos.model;

public enum ProgramSubTypes {

    FULL_DAY_DC, MORNING_HALF_DAY_DC, EVENING_HALF_DAY_DC, QUARTER_DAY_DC, ADHOC_DC, NIGHT_DC, INFANT_FULL_DAY_DC, INFANT_MORNING_HALF_DAY_DC, INFANT_EVENING_HALF_DAY_DC, INFANT_QUARTER_DAY_DC
}
