// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hmi.kiddos.model;

import com.hmi.kiddos.model.Admission;
import com.hmi.kiddos.model.AdmissionDataOnDemand;
import com.hmi.kiddos.model.Child;
import com.hmi.kiddos.model.ChildDataOnDemand;
import com.hmi.kiddos.model.TransportationDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect AdmissionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AdmissionDataOnDemand: @Component;
    
    private Random AdmissionDataOnDemand.rnd = new SecureRandom();
    
    private List<Admission> AdmissionDataOnDemand.data;
    
    @Autowired
    ChildDataOnDemand AdmissionDataOnDemand.childDataOnDemand;
    
    @Autowired
    TransportationDataOnDemand AdmissionDataOnDemand.transportationDataOnDemand;
    
    public Admission AdmissionDataOnDemand.getNewTransientAdmission(int index) {
        Admission obj = new Admission();
        setAdmissionDate(obj, index);
        setChild(obj, index);
        setDiscount(obj, index);
        setJoiningDate(obj, index);
        setNotes(obj, index);
        return obj;
    }
    
    public void AdmissionDataOnDemand.setAdmissionDate(Admission obj, int index) {
        Calendar admissionDate = Calendar.getInstance();
        obj.setAdmissionDate(admissionDate);
    }
    
    public void AdmissionDataOnDemand.setChild(Admission obj, int index) {
        Child child = childDataOnDemand.getRandomChild();
        obj.setChild(child);
    }
    
    public void AdmissionDataOnDemand.setDiscount(Admission obj, int index) {
        int discount = index;
        obj.setDiscount(discount);
    }
    
    public void AdmissionDataOnDemand.setJoiningDate(Admission obj, int index) {
        Calendar joiningDate = Calendar.getInstance();
        obj.setJoiningDate(joiningDate);
    }
    
    public void AdmissionDataOnDemand.setNotes(Admission obj, int index) {
        String notes = "notes_" + index;
        if (notes.length() > 400) {
            notes = notes.substring(0, 400);
        }
        obj.setNotes(notes);
    }
    
    public Admission AdmissionDataOnDemand.getSpecificAdmission(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Admission obj = data.get(index);
        Long id = obj.getId();
        return Admission.findAdmission(id);
    }
    
    public Admission AdmissionDataOnDemand.getRandomAdmission() {
        init();
        Admission obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Admission.findAdmission(id);
    }
    
    public boolean AdmissionDataOnDemand.modifyAdmission(Admission obj) {
        return false;
    }
    
    public void AdmissionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Admission.findAdmissionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Admission' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Admission>();
        for (int i = 0; i < 10; i++) {
            Admission obj = getNewTransientAdmission(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
