// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hmi.kiddos.model;

import com.hmi.kiddos.model.Centers;
import com.hmi.kiddos.model.Program;
import com.hmi.kiddos.model.ProgramDataOnDemand;
import com.hmi.kiddos.model.StaffDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ProgramDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProgramDataOnDemand: @Component;
    
    private Random ProgramDataOnDemand.rnd = new SecureRandom();
    
    private List<Program> ProgramDataOnDemand.data;
    
    @Autowired
    StaffDataOnDemand ProgramDataOnDemand.staffDataOnDemand;
    
    public Program ProgramDataOnDemand.getNewTransientProgram(int index) {
        Program obj = new Program();
        setBatch(obj, index);
        setCenter(obj, index);
        setDueDate(obj, index);
        setFees(obj, index);
        setNotes(obj, index);
        setTerm(obj, index);
        setType(obj, index);
        return obj;
    }
    
    public void ProgramDataOnDemand.setBatch(Program obj, int index) {
        String batch = "Undecided_" + index;
        obj.setBatch(batch);
    }
    
    public void ProgramDataOnDemand.setCenter(Program obj, int index) {
        Centers center = Centers.class.getEnumConstants()[0];
        obj.setCenter(center);
    }
    
    public void ProgramDataOnDemand.setDueDate(Program obj, int index) {
        Calendar dueDate = Calendar.getInstance();
        obj.setDueDate(dueDate);
    }
    
    public void ProgramDataOnDemand.setFees(Program obj, int index) {
        Integer fees = new Integer(index);
        if (fees < 1 || fees > 999999) {
            fees = 999999;
        }
        obj.setFees(fees);
    }
    
    public void ProgramDataOnDemand.setNotes(Program obj, int index) {
        String notes = "notes_" + index;
        obj.setNotes(notes);
    }
    
    public void ProgramDataOnDemand.setTerm(Program obj, int index) {
        String term = "term_" + index;
        obj.setTerm(term);
    }
    
    public void ProgramDataOnDemand.setType(Program obj, int index) {
        String type = "type_" + index;
        obj.setType(type);
    }
    
    public Program ProgramDataOnDemand.getSpecificProgram(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Program obj = data.get(index);
        Long id = obj.getId();
        return Program.findProgram(id);
    }
    
    public Program ProgramDataOnDemand.getRandomProgram() {
        init();
        Program obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Program.findProgram(id);
    }
    
    public boolean ProgramDataOnDemand.modifyProgram(Program obj) {
        return false;
    }
    
    public void ProgramDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Program.findProgramEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Program' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Program>();
        for (int i = 0; i < 10; i++) {
            Program obj = getNewTransientProgram(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
