// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hmi.kiddos.model;

import com.hmi.kiddos.model.TransportationIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TransportationIntegrationTest_Roo_Configurable {
    
    declare @type: TransportationIntegrationTest: @Configurable;
    
}
